[platformio]
default_envs = esp32-2432S028
src_dir = src
include_dir = include
lib_dir = lib

[env:esp32-2432S028]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
board_build.filesystem = littlefs

build_flags =
  -D USER_SETUP_LOADED=1
  -D ILI9341_2_DRIVER=1
  -D TFT_WIDTH=240
  -D TFT_HEIGHT=320
  -D LV_CONF_INCLUDE_SIMPLE
  -I src
  -I $PROJECT_LIBDEPS_DIR/$PIOENV/Meshtastic/src
  -I $PROJECT_LIBDEPS_DIR/$PIOENV/Meshtastic/src/meshtastic

lib_deps =
  lovyan03/LovyanGFX @ ^1.1.12
  bodmer/TFT_eSPI @ ^2.5.34
  lvgl/lvgl @ ^8.3.9
  https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
  Meshtastic
